workflows:
  ios-debug-build:
    name: Flutter Debug iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    # Rất quan trọng cho monorepo: Trỏ vào thư mục app
    working_directory: petties_mobile
    environment:
      groups:
        - google-service-account
      flutter: stable
      xcode: latest
    scripts:
      - name: Create .env if missing
        script: |
          # Ensure .env exists to prevent "No file found for asset: .env"
          if [ ! -f .env ]; then
            touch .env
            echo "API_BASE_URL=http://localhost:8080" > .env
          fi
      - name: Flutter pub get
        script: flutter pub get
      - name: Install Pods
        script: |
          cd ios
          pod install
      - name: Flutter build IPA
        script: flutter build ipa --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
