workflows:
  ios-release-build:
    name: Flutter Release iOS (for Sideloadly)
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: petties_mobile
    environment:
      groups:
        - google-service-account
      flutter: stable
      xcode: latest
      vars:
        COCOAPODS_DISABLE_STATS: "true"
    scripts:
      - name: Create .env if missing
        script: |
          if [ ! -f .env ]; then
            touch .env
            echo "API_BASE_URL=$API_BASE_URL" > .env
          fi
      - name: Flutter pub get
        script: flutter pub get
      - name: Configure Git and Install Pods
        script: |
          cd ios
          git config --global http.postBuffer 524288000
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999999
          n=0
          until [ "$n" -ge 3 ]
          do
             pod install && break
             n=$((n+1)) 
             echo "Pod install failed... retrying ($n/3)"
             sleep 5
          done
      - name: Flutter build iOS (Release)
        script: flutter build ios --release --no-codesign
      - name: Package IPA for Sideloading
        script: |
          # Xóa rác cũ nếu có
          rm -rf Payload Runner.ipa
          # Tạo cấu trúc IPA chuẩn: Payload/Runner.app
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -v -r Runner.ipa Payload
    artifacts:
      - petties_mobile/Runner.ipa
