export { default as StaffDashboardPage } from './DashboardPage'
export { default as StaffSchedulePage } from './StaffSchedulePage'
export { default as StaffBookingsPage } from './StaffBookingsPage'
export { CreateEmrPage } from './emr/CreateEmrPage'
export { EditEmrPage } from './emr/EditEmrPage'
export { EmrDetailPage } from './emr/EmrDetailPage'
export { StaffPatientsPage } from './patients'
export { NotificationsPage } from './NotificationsPage'
