// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_DXF6wrTuwMiP_AXo69CyamyZZl--JkM',
    appId: '1:620454234596:android:5ca04071d2ff84970adff1',
    messagingSenderId: '620454234596',
    projectId: 'petties-cd84e',
    databaseURL: 'https://petties-cd84e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petties-cd84e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQuQLs4-eLVfJo4U7K3oSHkUXzQMRzpaU',
    appId: '1:620454234596:ios:f5591036fcb0ed880adff1',
    messagingSenderId: '620454234596',
    projectId: 'petties-cd84e',
    databaseURL: 'https://petties-cd84e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petties-cd84e.firebasestorage.app',
    iosBundleId: 'world.petties.mobile',
  );
}
