"""
WebSocket Chat Constants

Định nghĩa các constants cho WebSocket chat handlers.

Package: app.api.websocket
"""

# WebSocket close reasons
WS_REASON_AUTH_REQUIRED = "CHAT_AUTH_REQUIRED"
WS_REASON_INVALID_AUTH = "CHAT_INVALID_AUTH"
WS_REASON_PLAYGROUND_FORBIDDEN = "CHAT_PLAYGROUND_FORBIDDEN"
WS_REASON_SESSION_FORBIDDEN = "CHAT_SESSION_FORBIDDEN"

__all__ = [
    "WS_REASON_AUTH_REQUIRED",
    "WS_REASON_INVALID_AUTH",
    "WS_REASON_PLAYGROUND_FORBIDDEN",
    "WS_REASON_SESSION_FORBIDDEN",
]
